paths:
  uploads: public/assets
  static:
  collections: ''
  data: ''
collections_config:
  work:
    path: src/content/work
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  pages:
    path: src/pages
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_inputs:
  img:
    type: image
    options:
      paths:
      mime_type:
      empty_type:
      resize_style: contain
      width:
      height:
      expandable:
      allowed_sources:
      prevent_resize_existing_files:
      sizes:
    cascade: true
timezone: Etc/UTC
